apiVersion: v1
kind: Pod
metadata:
 name: linuxjobber
 labels:
  app: linuxjobber
spec:
 containers:
 - name: ljdb
   image: mysql/mysql-server: latest
   env:
   - name: MYSQL_ROOT_PASSWORD
     value: 8iu7*IU&
   - name: MYSQL_DATABASE
     value: linuxjobber
   - name: "MYSQL_ROOT_HOST"
     value: "%"
   ports:
   - containerPort: 3306
  - name: linuxjobber
    image: linuxjobber
    ports:
    - containerPort: 4000
    - containerPort: 7000