apiVersion: v1
kind: Service
metadata:
 name: linuxjobber-port
 labels:
  name: linuxjobber-port
spec:
 type:NodePort
 ports:
 - port: 4000
   nodePort: 30100
   name: linuxjobber
 - port: 7000
   nodePort: 30000
   name: groupclass
 selector:
  app: linuxjobber